# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_taggable_simple}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Hollin R. Wilkins"]
  s.date = %q{2011-04-10}
  s.description = %q{
    Provides an acts_as_taggable method for ActiveRecord::Base, which
    allows your models to be tagged with arbitrary strings.

    This gem is written to rely completely on rails-generated SQL.
    This may change in the future, but the idea is that this gem should play nicely
    with other gems like meta_search.
  }
  s.email = %q{hrw7@cornell.edu}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "acts_as_taggable_simple.gemspec",
    "init.rb",
    "lib/active_record/acts/taggable.rb",
    "lib/acts_as_taggable_simple.rb",
    "lib/generators/acts_as_taggable_simple/migration/migration_generator.rb",
    "lib/generators/acts_as_taggable_simple/migration/templates/active_record/migration.rb",
    "lib/tag.rb",
    "lib/tag_list.rb",
    "lib/tagging.rb",
    "spec/acts_as_taggable_simple/acts_as_taggable_simple_spec.rb",
    "spec/acts_as_taggable_simple/spec_helper.rb",
    "spec/acts_as_taggable_simple/taggable_spec.rb",
    "spec/database.yml",
    "spec/models.rb",
    "spec/schema.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/chromaticbum/acts_as_taggable_simple}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Provides an acts_as_taggable method for ActiveRecord::Base}
  s.test_files = [
    "spec/acts_as_taggable_simple/acts_as_taggable_simple_spec.rb",
    "spec/acts_as_taggable_simple/spec_helper.rb",
    "spec/acts_as_taggable_simple/taggable_spec.rb",
    "spec/models.rb",
    "spec/schema.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.0.5"])
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.5"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.5"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

